# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcfbde63562804980d10e3975637934aa76cd342903db32d217e1fcd00bef0e13edbc29c8258543fd5f8109fbc22b8ec96c51ed894f0553ab86c148a8ec13b40

test:
  secret_key_base: 9c72238d1b99977158d08e4e6c1a6af66e9481a43cf1befe7d32a530688f05363a58631ba4ec04551e777142f34c425bbdd19efdad435cfb95d2b3794ee09aeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
